M48
; DRILL file {KiCad 9.0.4} date 2026-05-30T17:15:38+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-30T17:15:38+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X204.665Y-39.512
X204.665Y-86.462
X229.175Y-39.512
X229.175Y-86.462
M30
